### ISSUE TITLE
Please consider making model with a shaved face

### ISSUE THREAD

**Issue by chekalsky** [DenisSergeevitch/My-3d-copy#1]

**Comment by DenisSergeevitch** [comment]
Sorry, I have tried, but 5 minutes later after the shaving I already starting having a beard

**Comment by DenisSergeevitch** [comment]
Done (in 2d yet), thank you for contributing and a request:
![2021-05-02 00 27 34](https://user-images.githubusercontent.com/2140110/116796498-35151300-aadd-11eb-8e91-e9450859547e.jpg)
